---
- name: Install Nginx inside Docker container
  hosts: containers
  gather_facts: no
  tasks:
    - name: Install Nginx
      apt:
        name: nginx
        state: present
      connection: docker

    - name: Start Nginx service
      service:
        name: nginx
        state: started
        enabled: yes
      connection: docker

